include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true # I don't like when things are mixed
    sort_pub_dependencies: false # I like to group them how I want to
    avoid_dynamic_calls: true # Safer in some cases
    avoid_classes_with_only_static_members: false # That's something we accept to tidy our code
    use_decorated_box: false # In some cases it does not display the same way
