name: flutter_video_player
description: A new Flutter package project.
version: 1.0.0
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  volume_controller: ^2.0.4
  video_player: ^2.3.0
  auto_orientation: ^2.2.1
  screen_brightness: ^0.2.2
  flutter_meedu: ^8.0.0
  flutter_spinkit: ^5.1.0
  meta: ^1.8.0
  dart_vlc: ^0.3.0

  window_manager: ^0.2.7
  hotkey_manager: ^0.1.7
  wakelock: ^0.6.2
  shared_preferences: ^2.0.15
  helpers: ^1.1.4
  dio: ^4.0.6
  dio_smart_retry: ^1.3.2
  path_provider: ^2.0.11
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
 uses-material-design: true
 assets:
    - assets/icons/fast-forward.png
    - assets/icons/fullscreen.png
    - assets/icons/minimize.png
    - assets/icons/mute.png
    - assets/icons/play.png
    - assets/icons/pause.png
    - assets/icons/repeat.png
    - assets/icons/rewind.png
    - assets/icons/sound.png
    - assets/icons/picture-in-picture.png
    - assets/icons/fit.png
